/**
 * lib/questions.config.ts
 *
 * Configuration des 23 questions du questionnaire PA.
 * SOURCE UNIQUE — toute modification de question se fait ici.
 */

import type { QuestionnaireConfig } from './types';

export const SECTORS = [
  'Industrie / Manufacturing',
  'Retail / E-commerce',
  'BTP / Construction',
  'Services B2B',
  'Santé / Médico-social',
  'Finance / Assurance',
  'Transport / Logistique',
  'Agroalimentaire',
  'Technologie / SaaS',
  'Énergie / Utilities',
  'Hôtellerie / Restauration',
  'Immobilier',
  'Secteur public',
  'Association / ESS',
  'Autre',
] as const;

export const ERP_TOP30 = [
  { value: 'sap_s4hana', label: 'SAP S/4HANA', tier: 'tier1' },
  { value: 'sap_ecc', label: 'SAP ECC', tier: 'tier1' },
  { value: 'oracle_netsuite', label: 'Oracle NetSuite', tier: 'tier1' },
  { value: 'oracle_ebs', label: 'Oracle E-Business Suite', tier: 'tier1' },
  { value: 'ms_d365', label: 'Microsoft Dynamics 365', tier: 'tier1' },
  { value: 'sage_x3', label: 'Sage X3', tier: 'tier1' },
  { value: 'sage_100', label: 'Sage 100', tier: 'tier2' },
  { value: 'sage_50', label: 'Sage 50', tier: 'tier2' },
  { value: 'cegid_xrp', label: 'Cegid XRP Flex', tier: 'tier2' },
  { value: 'cegid_loop', label: 'Cegid Loop', tier: 'tier2' },
  { value: 'divalto', label: 'Divalto Infinity', tier: 'tier2' },
  { value: 'ebp', label: 'EBP', tier: 'tier2' },
  { value: 'odoo', label: 'Odoo', tier: 'tier2' },
  { value: 'sylob', label: 'Sylob', tier: 'niche' },
  { value: 'qualiac', label: 'Qualiac', tier: 'niche' },
  { value: 'proginov', label: 'Proginov', tier: 'niche' },
  { value: 'isagri', label: 'Isagri', tier: 'niche' },
  { value: 'silog', label: 'Silog', tier: 'niche' },
  { value: 'infor_m3', label: 'Infor M3', tier: 'tier2' },
  { value: 'infor_ln', label: 'Infor LN', tier: 'tier2' },
  { value: 'epicor', label: 'Epicor', tier: 'tier2' },
  { value: 'ifs', label: 'IFS', tier: 'tier2' },
  { value: 'workday', label: 'Workday Financials', tier: 'tier1' },
  { value: 'pennylane', label: 'Pennylane', tier: 'tier2' },
  { value: 'quickbooks', label: 'QuickBooks', tier: 'tier2' },
  { value: 'akuiteo', label: 'Akuiteo', tier: 'niche' },
  { value: 'custom', label: 'ERP développé en interne', tier: 'custom' },
  { value: 'other', label: 'Autre', tier: 'niche' },
  { value: 'none', label: 'Aucun ERP', tier: 'none' },
] as const;

export const QUESTIONNAIRE_CONFIG: QuestionnaireConfig = {
  version: '1.0.0',
  steps: [
    {
      id: 1,
      title: 'Contexte organisationnel',
      description: "Taille, secteur, périmètre géographique et deadline de la réforme.",
    },
    {
      id: 2,
      title: 'Architecture SI',
      description: 'ERP, logiciel comptable, outils P2P et briques existantes.',
    },
    {
      id: 3,
      title: 'Flux de facturation',
      description: 'Volumes émis/reçus, exceptions, B2G, auto-factures.',
    },
    {
      id: 4,
      title: 'Contraintes & exigences',
      description: 'Hébergement, certifications, budget, ressources internes.',
    },
    {
      id: 5,
      title: 'Priorités',
      description: 'Classer les critères de sélection par ordre d\'importance.',
    },
  ],

  questions: [
    // STEP 1 — CONTEXTE
    {
      id: 'company_size',
      step: 1,
      type: 'radio',
      label: 'Taille de l\'organisation',
      required: true,
      options: [
        { value: 'TPE', label: 'TPE', description: 'Moins de 10 salariés' },
        { value: 'PME', label: 'PME', description: '10 à 249 salariés' },
        { value: 'ETI', label: 'ETI', description: '250 à 4999 salariés' },
        { value: 'GE', label: 'Grande entreprise', description: '5000+ salariés' },
      ],
    },
    {
      id: 'sector',
      step: 1,
      type: 'select',
      label: 'Secteur d\'activité',
      required: true,
      options: SECTORS.map((s) => ({ value: s, label: s })),
    },
    {
      id: 'nb_entities',
      step: 1,
      type: 'radio',
      label: 'Nombre d\'entités juridiques',
      description: 'Périmètre à raccorder à la PA.',
      required: true,
      options: [
        { value: '1', label: '1 entité' },
        { value: '2-5', label: '2 à 5 entités' },
        { value: '6-20', label: '6 à 20 entités' },
        { value: '20+', label: 'Plus de 20 entités' },
      ],
    },
    {
      id: 'geography',
      step: 1,
      type: 'radio',
      label: 'Périmètre géographique',
      required: true,
      options: [
        { value: 'FRANCE', label: 'France uniquement' },
        { value: 'EU', label: 'Union Européenne' },
        { value: 'INTL', label: 'International (hors UE)' },
      ],
    },
    {
      id: 'deadline',
      step: 1,
      type: 'radio',
      label: 'Deadline cible de mise en conformité',
      required: true,
      options: [
        { value: '<3mois', label: 'Moins de 3 mois' },
        { value: '3-6mois', label: '3 à 6 mois' },
        { value: '6-12mois', label: '6 à 12 mois' },
        { value: '>12mois', label: 'Plus de 12 mois' },
      ],
    },

    // STEP 2 — ARCHITECTURE SI
    {
      id: 'erp_main',
      step: 2,
      type: 'select',
      label: 'ERP principal',
      description: 'Le système qui émet la majorité des factures.',
      required: true,
      searchable: true,
      options: ERP_TOP30.map((e) => ({ value: e.value, label: e.label })),
    },
    {
      id: 'erp_tier',
      step: 2,
      type: 'radio',
      label: 'Classification de l\'ERP',
      description: 'Pré-rempli automatiquement à partir de l\'ERP choisi, ajustable.',
      required: true,
      options: [
        { value: 'tier1', label: 'Tier 1', description: 'SAP, Oracle, MS Dynamics, Sage X3...' },
        { value: 'tier2', label: 'Tier 2', description: 'Sage 100, Cegid, Odoo, Divalto...' },
        { value: 'niche', label: 'Niche / sectoriel', description: 'Sylob, Qualiac, Isagri...' },
        { value: 'custom', label: 'Spécifique / interne' },
        { value: 'none', label: 'Aucun ERP' },
      ],
    },
    {
      id: 'accounting_software',
      step: 2,
      type: 'select',
      label: 'Logiciel comptable',
      required: true,
      options: [
        { value: 'same_as_erp', label: 'Même que l\'ERP' },
        { value: 'sage_100', label: 'Sage 100 Compta' },
        { value: 'sage_generation', label: 'Sage Génération Experts' },
        { value: 'cegid_quadra', label: 'Cegid Quadra' },
        { value: 'cegid_loop', label: 'Cegid Loop' },
        { value: 'sap_fi', label: 'SAP FI' },
        { value: 'pennylane', label: 'Pennylane' },
        { value: 'ebp_compta', label: 'EBP Compta' },
        { value: 'fulll', label: 'Fulll' },
        { value: 'other', label: 'Autre' },
      ],
    },
    {
      id: 'p2p_tool',
      step: 2,
      type: 'select',
      label: 'Outil P2P / e-procurement',
      description: 'Gestion des factures fournisseurs, bons de commande, validation.',
      required: true,
      options: [
        { value: 'none', label: 'Aucun' },
        { value: 'ivalua', label: 'Ivalua' },
        { value: 'coupa', label: 'Coupa' },
        { value: 'sap_ariba', label: 'SAP Ariba' },
        { value: 'jaggaer', label: 'Jaggaer' },
        { value: 'basware', label: 'Basware' },
        { value: 'esker', label: 'Esker P2P' },
        { value: 'yooz', label: 'Yooz' },
        { value: 'other', label: 'Autre' },
      ],
    },
    {
      id: 'invoice_format_out',
      step: 2,
      type: 'radio',
      label: 'Format de facture émise aujourd\'hui',
      required: true,
      options: [
        { value: 'PDF', label: 'PDF (email / courrier)' },
        { value: 'EDI', label: 'EDI' },
        { value: 'mixed', label: 'Mixte PDF + EDI' },
        { value: 'other', label: 'Autre' },
      ],
    },
    {
      id: 'archiving',
      step: 2,
      type: 'radio',
      label: 'Solution d\'archivage actuelle',
      required: true,
      options: [
        { value: 'GED', label: 'GED' },
        { value: 'SAE', label: 'SAE (probant)' },
        { value: 'none', label: 'Aucun' },
        { value: 'tbd', label: 'À définir' },
      ],
    },
    {
      id: 'has_od_sc',
      step: 2,
      type: 'radio',
      label: 'Avez-vous déjà choisi un OD / PA ?',
      required: true,
      options: [
        { value: 'yes', label: 'Oui' },
        { value: 'no', label: 'Non' },
        { value: 'in_progress', label: 'En cours de sélection' },
      ],
    },

    // STEP 3 — FLUX
    {
      id: 'volume_emitted',
      step: 3,
      type: 'radio',
      label: 'Volume annuel de factures émises',
      required: true,
      options: [
        { value: '<100', label: 'Moins de 100' },
        { value: '100-500', label: '100 à 500' },
        { value: '500-2000', label: '500 à 2 000' },
        { value: '2000-10000', label: '2 000 à 10 000' },
        { value: '>10000', label: 'Plus de 10 000' },
      ],
    },
    {
      id: 'volume_received',
      step: 3,
      type: 'radio',
      label: 'Volume annuel de factures reçues',
      required: true,
      options: [
        { value: '<100', label: 'Moins de 100' },
        { value: '100-500', label: '100 à 500' },
        { value: '500-2000', label: '500 à 2 000' },
        { value: '2000-10000', label: '2 000 à 10 000' },
        { value: '>10000', label: 'Plus de 10 000' },
      ],
    },
    {
      id: 'exception_rate',
      step: 3,
      type: 'radio',
      label: 'Taux d\'exceptions / litiges',
      required: true,
      options: [
        { value: '<5%', label: 'Moins de 5%' },
        { value: '5-15%', label: '5 à 15%' },
        { value: '15-30%', label: '15 à 30%' },
        { value: '>30%', label: 'Plus de 30%' },
      ],
    },
    {
      id: 'nb_approvers',
      step: 3,
      type: 'radio',
      label: 'Nombre d\'approbateurs sur le circuit',
      required: true,
      options: [
        { value: '1', label: '1 approbateur' },
        { value: '2-3', label: '2 à 3 approbateurs' },
        { value: '4+', label: '4 approbateurs ou plus' },
        { value: 'variable', label: 'Variable selon facture' },
      ],
    },
    {
      id: 'has_b2g',
      step: 3,
      type: 'radio',
      label: 'Facturation B2G (Chorus Pro) ?',
      required: true,
      options: [
        { value: 'yes', label: 'Oui, aujourd\'hui' },
        { value: 'no', label: 'Non' },
        { value: 'future', label: 'Pas aujourd\'hui mais prévu' },
      ],
    },
    {
      id: 'has_autofactures',
      step: 3,
      type: 'radio',
      label: 'Gestion d\'auto-factures (self-billing) ?',
      required: true,
      options: [
        { value: 'yes', label: 'Oui' },
        { value: 'no', label: 'Non' },
        { value: 'tbd', label: 'À analyser' },
      ],
    },

    // STEP 4 — CONTRAINTES
    {
      id: 'data_hosting',
      step: 4,
      type: 'radio',
      label: 'Exigence d\'hébergement des données',
      required: true,
      options: [
        { value: 'FRANCE', label: 'France uniquement' },
        { value: 'EU', label: 'Union Européenne' },
        { value: 'INTL', label: 'International acceptable' },
      ],
    },
    {
      id: 'certifications',
      step: 4,
      type: 'multiselect',
      label: 'Certifications requises',
      description: 'Plusieurs choix possibles.',
      required: false,
      options: [
        { value: 'ISO27001', label: 'ISO 27001' },
        { value: 'HDS', label: 'HDS (santé)' },
        { value: 'SecNumCloud', label: 'SecNumCloud' },
        { value: 'NF_Z42013', label: 'NF Z 42-013 (archivage probant)' },
        { value: 'none', label: 'Aucune exigence particulière' },
      ],
    },
    {
      id: 'archiving_probant',
      step: 4,
      type: 'radio',
      label: 'Archivage probant (10 ans, horodaté) requis ?',
      required: true,
      options: [
        { value: 'yes', label: 'Oui, obligatoire' },
        { value: 'no', label: 'Non' },
        { value: 'tbd', label: 'À définir' },
      ],
    },
    {
      id: 'budget_monthly',
      step: 4,
      type: 'radio',
      label: 'Budget mensuel indicatif pour la PA',
      required: true,
      options: [
        { value: '<500', label: 'Moins de 500 €' },
        { value: '500-2k', label: '500 € à 2 000 €' },
        { value: '2k-5k', label: '2 000 € à 5 000 €' },
        { value: '>5k', label: 'Plus de 5 000 €' },
        { value: 'undefined', label: 'Non défini' },
      ],
    },
    {
      id: 'internal_resources',
      step: 4,
      type: 'radio',
      label: 'Ressources internes pour le projet',
      required: true,
      options: [
        { value: 'dedicated', label: 'Équipe IT dédiée' },
        { value: 'partial', label: 'IT partielle' },
        { value: 'none', label: 'Aucune ressource IT interne' },
      ],
    },

    // STEP 5 — PRIORITÉS
    {
      id: 'priorities',
      step: 5,
      type: 'ranking',
      label: 'Classez vos priorités par ordre d\'importance',
      description: 'Le critère en 1ère position pèsera le plus lourd dans la shortlist.',
      required: true,
      options: [
        { value: 'erp_integration', label: 'Intégration ERP native', description: 'Connecteur prêt à l\'emploi avec votre ERP' },
        { value: 'functional_coverage', label: 'Couverture fonctionnelle', description: 'Richesse des modules O2C / P2P' },
        { value: 'cost', label: 'Coût total', description: 'Licence, mise en œuvre, run' },
        { value: 'support_quality', label: 'Qualité du support', description: 'Support FR, SLA, accompagnement' },
        { value: 'security_sovereignty', label: 'Sécurité & souveraineté', description: 'Hébergement FR, certifications' },
      ],
    },
  ],
};
